export const ErrorCode = {
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  CHAT_ARCHIVED: 'CHAT_ARCHIVED',
  AI_RUN_NOT_FOUND: 'AI_RUN_NOT_FOUND',
  AI_RUN_IN_FLIGHT: 'AI_RUN_IN_FLIGHT',
  AI_RUN_CONFLICT: 'AI_RUN_CONFLICT',
  MESSAGE_CONFLICT: 'MESSAGE_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  AUTH_NOT_CONFIGURED: 'AUTH_NOT_CONFIGURED',
  AUTH_FAILURE: 'AUTH_FAILURE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiError {
  readonly code: ErrorCode;
  readonly message: string;
}
